settings_version: 0.0.5
datasets_dir: /root/datasets
weights_dir: weights
runs_dir: runs
uuid: bc6dcb0730af79a27a7c804540c58c91de05d66dc18411a75c92dee88388a3a4
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
vscode_msg: true
