; [Settings]
; in_url_list = rtsp://210.99.70.120:1935/live/cctv001.stream,
;               rtsp://210.99.70.120:1935/live/cctv002.stream,
;               rtsp://210.99.70.120:1935/live/cctv003.stream,
;               rtsp://210.99.70.120:1935/live/cctv004.stream,
;               rtsp://210.99.70.120:1935/live/cctv005.stream,
;               rtsp://210.99.70.120:1935/live/cctv006.stream,
;               rtsp://210.99.70.120:1935/live/cctv007.stream,
;               rtsp://210.99.70.120:1935/live/cctv008.stream,
;               rtsp://210.99.70.120:1935/live/cctv009.stream,
;               rtsp://210.99.70.120:1935/live/cctv010.stream
; out_path_list = out01,
;                 out02,
;                 out03,
;                 out04,
;                 out05,
;                 out06,
;                 out07,
;                 out08,
;                 out09,
;                 out10
